### ISSUE TITLE
有考虑接下来扩展到手机端吗

### ISSUE THREAD

**Issue by silverbullet1472** [goolhanrry/SeatKiller_UI#3]

**Comment by silverbullet1472** [comment]
这个东西也太cool了吧，有一些idea：
- 需求的根源：图书馆资源配置不均&自习室的好坏选择
- 几个图书馆的评价：轻度或重度使用->体现可达性&公平性
- 单个图书馆服务的分配：云桌面&讨论区&木桌

自己的感觉↓
> SeatKiller的终极goal，应该是帮助每一个图书馆使用者都无需使用SeatKiller了

**Comment by yeliudev** [comment]
桌面版确实不方便...我自己是一直挂在 vps 上跑的，手机用远程桌面连上去操作

实在腾不出时间移植到移动端了，大佬有空可以搞一搞啊
