### ISSUE TITLE
建议删了

### ISSUE THREAD

**Issue by DXWEIE** [goolhanrry/SeatKiller_UI#9]
非常的不爽啊，平常经常约的位置被人用软件刷了，都想自己写个脚本了，建议把这个下线了

**Comment by goolhanrry** [comment]
大家都在写脚本，为什么非要我下线呢？更何况其他人要么弹窗支付宝，要么强制star或者推广。我写这个这软件一是为了练手，二放出来也是为了方便大家应对各种脚本的争夺。我也非常赞成大家都按规定来，但是到目前为止，学校没能完全杜绝非正常访问，某些人的强制推广软件也还在继续更新，所以尽管我已经没有维护，但是在问题解决之前，我不会考虑下线。
